language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test --coverage --coverageReporters=text-lcov > coverage.report
before_deploy: npm build
after_deploy: cat coverage.report | npm run coveralls
